### ISSUE TITLE
Will this continue to be maintained?

### ISSUE THREAD

**Issue by lmartins** [Shopify/theme-scripts#118]
My apologies for opening a ticket just for this, but granted what happened with Slate, and how poorly that whole situation have unfolded, I'd love to get clarity from the maintainers of this repo if it will continue to be maintained or if, like Slate, will be abandoned.

https://shopify.github.io/slate/docs/about

Thank you.

**Comment by chrisberthe** [comment]
Hey @lmartins, thanks for reaching out. For the time being, we have no intention of abandoning these scripts. While activity for this repository is pretty sparse, we're still adding to it when we can and will continue to do so.

**Comment by lmartins** [comment]
Thank you for @chrisberthe shedding some light into that.
