### ISSUE TITLE
Trying to load a section without ID specified should throw an error

### ISSUE THREAD

**Issue by rmfarrell** [Shopify/theme-scripts#12]
I'm trying to use this on a page with multiple product sections. I have the following code, which comes with Slate.

```
$(document).ready(() => {
  sections.load('product');
});
```

I would expect it to load every product on the page or at least expose an option to load multiple but I can't find them

**Comment by rmfarrell** [comment]
To answer my own question, after going through source code a bit, it looks like I failed to give my sections a unique ID.

Could this throw an error?
Also, is it worth noting in the docs?

**Comment by t-kelly** [comment]
@shopify/theme-sections v1.1.0 throws errors when `load()` is called without an ID:
https://github.com/Shopify/theme-scripts/blob/78b864c2f49cca0379609c969dd189152dc20c15/packages/theme-sections/section.js#L40-L46
