### ISSUE TITLE
Is this compatible with Debut theme?

### ISSUE THREAD

**Issue by alxvallejo** [Shopify/theme-scripts#120]
There's no package.json out of the box. No webpack. Not sure if ES6 is supported. No documentation anywhere. Slate theme is deprecated. This library isn't maintained. WTF Shopify.

**Comment by chrisberthe** [comment]
>There's no package.json out of the box. No webpack. Not sure if ES6 is supported. This library isn't maintained. 

Not sure I follow - can you clarify? These are individual node modules you can bring into your own theme project. There wouldn't be a need to use Webpack, ES6 depends on what browsers you need to target for your project, and while we're not extremely active on this repository, it is no way deprecated and we will continue to add to it over time.
