### ISSUE TITLE
theme-cart@latest is no longer available on unpkg

### ISSUE THREAD

**Issue by mrkstwrt** [Shopify/theme-scripts#127]
It seems that the unpkg hosted version of theme-cart has gone missing recently, I was using this without issue and it's started 404ing today.

Specific versions seem to work, which is fine if you catch this but I'm sure there's plenty of people using @latest out there

https://unpkg.com/@shopify/theme-cart@latest/dist/theme-cart.min.js

**Comment by chrisberthe** [comment]
Seems to have been an issue on unpkg's side - the link you provided works.

**Comment by t-kelly** [comment]
Can confirm it works on my end. Closing!
