### ISSUE TITLE
theme-cart, fetchJSON get Shopify's api error description

### ISSUE THREAD

**Issue by BryanYeh** [Shopify/theme-scripts#144]
If somehow in anyway, a buyer added more than what is available there is an error that is returned by Shopify api.
```json
{
  "status": 422,
  "message": "Cart Error",
  "description": "You can't add more Messenger Bag to the cart."
}
```
I know an error is thrown in [L16](https://github.com/Shopify/theme-scripts/blob/a903aad6e13abe319fc23345024ca16f5abb0056/packages/theme-cart/request.js#L16), it doesn't throw the error that the Shopify api returns. How do I get the error description from the Shopify api?
```js
// theme-cart/request.js start L13
function fetchJSON(url, config) {
  return fetch(url, config).then(function(response) {
    if (!response.ok) {
      throw response;
    }
    return response.json();
  });
}
```

**Comment by savchukoleksii** [comment]
@BryanYeh @t-kelly  
Shopify return 422 error using /cart/add.js endpoint only if Content-Type is application/x-www-form-urlencoded. Found out this during replicating jQuery.post method. So you can test something like that to implement 422 error logic:
```
axios.post('/cart/add.js', qs.stringify({
  | "items": [
  | {
  | id: parsedData.id,
  | quantity: 1
  | }
  | ]
  | }), {
  | headers: {
  | 'Accept': '*/*',
  | 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
  | 'X-Requested-With': 'XMLHttpRequest'
  | },
  | })
```

**Comment by BryanYeh** [comment]
@savchukoleksii 
Since I was already using `theme-cart` I wanted to avoid creating extra functions to query the endpoint.
I ended up editing it to my needs.

**Comment by savchukoleksii** [comment]
@BryanYeh I think that changing Content-Type will help here:
https://github.com/Shopify/theme-scripts/blob/master/packages/theme-cart/request.js#L7

**Comment by BryanYeh** [comment]
Ok, I found out the problem. I should have used `catch`.
```js
cart.addItem(...)
   .then((result) => {...})
   .catch((error) => {
      console.log(error.message)
   });
```
Now for some reason I am getting `undefinded` from `error.message`
which should have been **The product 'A Sample Product' is already sold out.**

**Comment by BryanYeh** [comment]
Ok, got it sorted out. Had some help in discord, and found out it has to be this way for it to work.
```js
.catch((error) => {
  error.json()
    .then((a)=>{
      console.log(a.description)
    })
})
```
Thank you @savchukoleksii for taking the time trying to help
