### ISSUE TITLE
Add shopify_common.js module

### ISSUE THREAD

**Issue by montalvomiguelo** [Shopify/theme-scripts#20]
### Problem

Starter theme uses `Shopify.CountryProvinceSelector()` and `Shopify.postLink()` in [customers/addresses.js](https://github.com/Shopify/starter-theme/blob/master/src/assets/scripts/templates/customers/addresses.js#L15-L24) but `shopify_common.js` is not loaded and the following error is produced

<img width="560" alt="screen shot 2018-06-19 at 6 45 03 pm" src="https://user-images.githubusercontent.com/5134470/41629772-ebf93186-73f0-11e8-8bfe-aa0aa59ec4a1.png">

### shopify_common.js

Contains functions to update the contents of the Province `<select>` as you select different values in the Country `<select>`

### Adding it as another package

If we had this functions in another package in theme-scripts we could use it as dependency in starter-theme

_package.json_
```diff
  "dependencies": {
+   "@shopify/theme-common": "^1.0.0-alpha.3",
    "@shopify/theme-a11y": "^1.0.0-alpha.3",
    "@shopify/theme-cart": "^1.0.0-alpha.3",
    "@shopify/theme-currency": "^1.0.0-alpha.3",
```

_src/assets/scripts/templates/customers/addresses.js_
```diff
 import $ from 'jquery';
+import { CountryProvinceSelector, postLink } from '@shopify/theme-common';

-new Shopify.CountryProvinceSelector(countrySelector, provinceSelector, {
+new CountryProvinceSelector(countrySelector, provinceSelector, {

-Shopify.postLink(`/account/addresses/${formId}`, {
+postLink(`/account/addresses/${formId}`, {
```

**Comment by huguestennier** [comment]
A [PR has been open](https://github.com/Shopify/starter-theme/pull/111) on Starter-theme to fix it - closing this issue.
