### ISSUE TITLE
Themes that use global variables cannot use theme-sections scripts

### ISSUE THREAD

**Issue by jeremystephencobb** [Shopify/theme-scripts#21]
### Issue

Themes that use IFFE's and assign to global variables, built with ES5 instead of ES6 `import / require`, cannot use `theme-section.js`.

As the theme editor receives updates and `theme-secions` is updated accordingly, it would be very helpful to have a version of this script that is compatible with how older themes are written.

### Example

For example, when a slideshow section in removed from the editor, a developer can use the `onUnLoad` function in the theme's js, which binds that function to the editor event.

The events are all given an event that can be called from the section's file except the `onLoad` event, which only creates an instance of that section type.

The editor's `show / hide` action is different than adding a new section instance, and creates situations where developers need to be able to call the `onLoad` event.

The latest version of `theme-sections.js` has a `load` event, but this file is not compatible with older themes, so developers cannot take advantage of this new functionality.

### Proposed solution

Create a version of these scripts that creates a global variable available to the page.

**Comment by t-kelly** [comment]
Done! https://github.com/Shopify/theme-scripts/blob/master/packages/theme-sections/README.md
