### ISSUE TITLE
Price change not reflected when choosing variant unless making the following change

### ISSUE THREAD

**Issue by wzowee** [Shopify/theme-scripts#25]
On a  new theme I was unable to get the prices change to update without making a code change to

https://github.com/Shopify/theme-scripts/blob/b199e9345acd1b400137ebcec8b2e27dd5ce9059/packages/theme-variants/variants.js#L90

I've changed it in my local and deployed copy to be

`satisfied = option.value == variant.id;`

Which then worked in terms of matching on the currently selected variant and propagating this back up.

The theme is live here - https://www.clairestelleprintshop.com/collections/world-travels/products/nepal-mountains-i?variant=8670059653

**Comment by chrisberthe** [comment]
Closing this issue - see https://github.com/Shopify/theme-scripts/pull/79.
