### ISSUE TITLE
cart.js redirecting to /cart (theme-cart)

### ISSUE THREAD

**Issue by dan-gamble** [Shopify/theme-scripts#46]
For some reason unless i change `getDefaultRequestConfig()` to:

```javascript
function getDefaultRequestConfig() {
  return {
    credentials: 'same-origin',
    headers: {
      'X-Requested-With': 'XMLHttpRequest',
      'Content-Type': 'application/json;'
    },
    method: 'GET'
  };
}
```

The `fetchJSON` method seems to fall back to `POST`. So when i call `getState` `request.cart()` seems to `POST` to `cart.js`.

This only happens on `deploy`. Doesn't seem to when locally developing.

![img](https://i.imgur.com/eMyzP5G.png)
![img2](https://i.imgur.com/a7x8diQ.png)

Changing `getDefaultRequestConfig()` to:

```javascript
function getDefaultRequestConfig() {
  return Object.assign({}, {
    credentials: 'same-origin',
    headers: {
      'X-Requested-With': 'XMLHttpRequest',
      'Content-Type': 'application/json;'
    }
  });
}
```

Seems to work. Happy to PR this in if that's an acceptable fix 👍

**Comment by t-kelly** [comment]
Fixed in `1.0.1`! https://github.com/Shopify/theme-scripts/pull/54

**Comment by t-kelly** [comment]
(Can't use Object.assign() since we're trying to stick to ES5 and avoid Babel to keep the libraries as tiny as possible)

**Comment by dan-gamble** [comment]
Awesome, thanks @t-kelly!
