### ISSUE TITLE
theme-sections: pass entire event into editor events

### ISSUE THREAD

**Issue by oscarstranger** [Shopify/theme-scripts#68]
Currently, the `theme-sections` callbacks such as `onLoad()` and `onBlockSelect()` only include certain `event.detail` parameters instead of the entire `event`. This makes targeting of elements, particularly blocks, cumbersome as you cannot access objects such as `event.target` inside section js files.

These callbacks should be modified to include the entire `event` object as a single parameter instead of multiple nested parameters, this would also keep theme-sections.js inline with the editor API documentation as seen here: https://help.shopify.com/en/themes/development/sections#javascript-and-stylesheet-tags

For example: 
```
document.addEventListener('shopify:block:select', function(event) {
  var instance = getInstanceById(event.detail.sectionId);

  if (typeof instance === 'object') {
    instance.onBlockSelect(event.detail.blockId, event.detail.load);
  }
});
```

Would become:
```
document.addEventListener('shopify:block:select', function(event) {
  var instance = getInstanceById(event.detail.sectionId);

  if (typeof instance === 'object') {
    instance.onBlockSelect(event);
  }
});
```
Attributes such as `blockId` and `load` would still be accessible from these callbacks via the `event.detail` object

**Comment by t-kelly** [comment]
Very well structured argument. I agree!
