### ISSUE TITLE
currency.js uses hardcoded currency formatting does not support multi-currency

### ISSUE THREAD

**Issue by davejcameron** [Shopify/theme-scripts#73]
The following line of code has a `$` symbol for the currency formatting:
https://github.com/Shopify/theme-scripts/blob/master/packages/theme-currency/currency.js#L11

This means that the cart will not update to reflect the currency being used in multi-currency.

You can get the current currency on cart by accessing `Shopify.currency.active`

**Comment by davejcameron** [comment]
Looks like the issue isn't with the function itself, you just need to make sure when calling this function that you also include `theme.moneyFormat` to get the appropriate formatting.

**Comment by t-kelly** [comment]
To be fair - the lib could use some documentation 😅

**Comment by drewlonious** [comment]
> To be fair - the lib could use some documentation 😅

yes, is it possible to get better documentation on these scripts? Would be so helpful
