### ISSUE TITLE
README: Incorrect example for updateAttributes()

### ISSUE THREAD

**Issue by justinmetros** [Shopify/theme-scripts#75]
Currently README for updateAttributes() has:
``` javascript
cart.getAttributes({ giftWrapped: false }).then(state => {
  if (state.attributes.giftWrapped) {
    console.log('The customer wants their order gift wrapped.');
  }
});
```

Should be:
``` javascript
cart.updateAttributes({ giftWrapped: false }).then(state => {
  if (state.attributes.giftWrapped) {
    console.log('The customer wants their order gift wrapped.');
  }
});
```

Tiny little thing, but hey. 

BTW I really like this package👍 Just finished updating a big plus site to use this for all cart operations and its been a joy to work with.

**Comment by justinmetros** [comment]
My bad - put this on the mono-repo. Its for [@shopify/theme-cart](https://github.com/Shopify/theme-scripts/tree/master/packages/theme-cart)

**Comment by t-kelly** [comment]
Fixed! Open a PR next time and I'll merge it 😄
