### ISSUE TITLE
theme-images: Cannot read property 'loadImage' of undefined (images.cjs.js)

### ISSUE THREAD

**Issue by el-rotny** [Shopify/theme-scripts#8]
When trying to preload images, browser complains about `this` not being defined. 

https://github.com/Shopify/theme-scripts/blob/1c415adbdf3b9d51065f5570cd765d2e8e28ecec/packages/theme-images/images.cjs.js#L32

Tested and an image array from json is being passed. Using it in the same way as https://github.com/Shopify/starter-theme/blob/master/src/assets/scripts/sections/product.js#L70

```
preload(this.productSingleObject.images, this.settings.imageSize);
```

**Comment by chrisberthe** [comment]
@el-rotny this was fixed in https://github.com/Shopify/theme-scripts/pull/9. Mind seeing if this helps? Going to close for now, but please report back if you encounter any other issues.
