### ISSUE TITLE
[Discussion] Should this repo adhere to the Conventional Commits guideline

### ISSUE THREAD

**Issue by antoinegrant** [Shopify/theme-scripts#89]
As we add more packages to this repo, it will become more important to automate updating  CHANGELOG. [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0-beta.3/) makes it much easier to manage CHANGELOG and [lerna supports it out of the box](https://github.com/lerna/lerna/tree/2.x#--conventional-commits) (we currently use [lera@2.9.0](https://github.com/lerna/lerna/tree/2.x))

@Shopify/themes-fed

**Comment by wizardlyhel** [comment]
The more that we can automate the deploy process, the better. I am 💯 on this

**Comment by t-kelly** [comment]
I have mixed feelings about automating changelog.. we've had good and bad experiences with this in themes in the past. The nice part about how things are setup now is that its a combination of automation + manual so that you can always tweak the output if something is missing or if something is there that shouldn't be. We had a ruby gem that was fully automated and that just caused so many headaches..

Not saying no.. but we should have an escape plan if we find ourselves spending a lot of time fixing the automation?

**Comment by wizardlyhel** [comment]
So .. I played around with Lerna's conventional commit on Slate.

```bash
slate $ yarn lerna -- version --conventional-commits
lerna notice cli v3.11.0
lerna info current version 1.0.0-beta.17
lerna info Looking for changed packages since v1.0.0-beta.17

Changes:
 - @shopify/slate-sections-plugin: 1.0.0-beta.17 => 1.0.0
 - @shopify/slate-tools: 1.0.0-beta.17 => 1.0.0
 - @shopify/slate-translations: 1.0.0-beta.17 => 1.0.0

? Are you sure you want to create these versions? Yes
lerna info execute Skipping GitHub releases
lerna info git Pushing tags...
lerna success version finished
✨  Done in 26.57s.
```
The above command created a commit on Slate master - https://github.com/Shopify/slate/commit/c3c28db2c64c1e8f40349d43b94c9d7c6924c00d

This commit completed the following:
- [x] Created a version tag
- [x] Updated all changed packages versions
- [x] Added to root CHANGELOG.md
- Generated CHANGELOG.md for individual package (Debate-able if we want this)

_Note: The above tag and commit is reverted on Slate_

We can make sure Slate is always in beta with the following command:

```bash
slate $ yarn lerna -- version prerelease
lerna notice cli v3.11.0
lerna info current version 1.0.0-beta.17
lerna info Looking for changed packages since v1.0.0-beta.17

Changes:
 - @shopify/slate-sections-plugin: 1.0.0-beta.17 => 1.0.0-beta.18
 - @shopify/slate-tools: 1.0.0-beta.17 => 1.0.0-beta.18
 - @shopify/slate-translations: 1.0.0-beta.17 => 1.0.0-beta.18

? Are you sure you want to create these versions? No
✨  Done in 21.08s.
```

One thing we need to be aware of is how we can introduce commit convention. Right now, Slate is using `lerna-changelog`. This generates change log details where you would need to manually edit the file to include it.

**Comment by jalada** [comment]
As a general feeling, a changelog would be great in this repo! I'm working on a theme that is on version ~1 and it makes me nervous seeing that I am two major versions behind, but I can't tell what the breaking changes are without diving into the commit history...

**Comment by av13t** [comment]
closing to address when we have more bandwidth
