### ISSUE TITLE
Update addItem to accept a form element

### ISSUE THREAD

**Issue by martinamarien** [Shopify/theme-scripts#93]
## Current state
Currently, theme-cart's `addItem()` accepts `id, {quantity, properties}`. This requires the theme developer to extract the `id`, and possibly the `quantity` and `properties` from the form to be able to add an item to the cart. 

Some work arounds could include using regex or FormData to get this information. However, currently FormData would require a polyfill to support IE. This could also be frustrating to implement on multiple themes.

## Suggestion
When interacting with the Shopify AJAX API directly, you can simply pass a `serialized()` form with Jquery. 

Similarly, we're suggesting that `addItem()` accepts a form element. It could then use something like FormData to extract the id, quantity and properties. By changing the `additem()` functionality, `theme-cart` could then handle the implementation of the polyfill.

**Comment by t-kelly** [comment]
All 👍 except instead of extending `addItem()`, I would rather a new method to stay concise, eg. `addItemByForm()`

**Comment by eballeste** [comment]
`addItemFromForm`

**Comment by NathanPJF** [comment]
@bimalbhagrath Assigning to you as discussed IRL.

@martinamarien will be the best point of contact to get more context on the problem. Reviewers would be @wizardlyhel or @t-kelly
