### ISSUE TITLE
Theme Product => getProductJson is wrong

### ISSUE THREAD

**Issue by shelldandy** [Shopify/theme-scripts#94]
https://github.com/Shopify/theme-scripts/blob/d0a9ea16970b175512ae7aacf6bf7af98c6bbc2c/packages/theme-product/theme-product.js#L5-L9

`fetch('/product/' + handle + '.js')`

should be: fetch('/products/' + handle + '.js')

**Comment by huguestennier** [comment]
Fixed in https://github.com/Shopify/theme-scripts/pull/95
